---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - mail-config.yaml
patchesStrategicMerge:
  - configPatch.yml
  - platformPatch.yaml
  - ingressPatch.yaml
...
